[project]
name = "nvd"
version = "0.1.0"
description = "National Vulnerability Database Toolkit"
readme = "README.md"
authors = [{ name = "Tory Clasen", email = "ToryClasen@gmail.com" }]
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.11.5",
    "sqlalchemy[asyncio]>=2.0.41",
    "sqlmodel>=0.0.24",
]

[project.scripts]
nvd = "nvd:main"

[project.optional-dependencies]
sqlite = ["aiosqlite>=0.21.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.mypy]
plugins = ["pydantic.mypy"]
